// Date: 8/31/2013 10:51:47 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package fossils.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelSpino extends ModelBase
{
  //fields
    ModelRenderer Upper_Jaw;
    ModelRenderer Lower_Jaw;
    ModelRenderer Head;
    ModelRenderer Teeth;
    ModelRenderer Neck;
    ModelRenderer Crest;
    ModelRenderer Upper_Body;
    ModelRenderer Lower_Body;
    ModelRenderer Tail1;
    ModelRenderer Tail2;
    ModelRenderer Tail3;
    ModelRenderer Thigh1;
    ModelRenderer Thigh2;
    ModelRenderer Calf1;
    ModelRenderer Calf2;
    ModelRenderer Foot1;
    ModelRenderer Foot2;
    ModelRenderer UpperArm1;
    ModelRenderer UpperArm2;
    ModelRenderer LowerArm1;
    ModelRenderer LowerArm2;
    ModelRenderer Sail1;
    ModelRenderer Sail2;
    ModelRenderer Sail3;
    ModelRenderer Sail4;
    ModelRenderer Sail5;
    ModelRenderer Sail6;
    ModelRenderer Sail7;
  
  public ModelSpino()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      Upper_Jaw = new ModelRenderer(this, 0, 10);
      Upper_Jaw.addBox(0F, 0F, 0F, 4, 3, 7);
      Upper_Jaw.setRotationPoint(0F, 0F, 0F);
      Upper_Jaw.setTextureSize(64, 64);
      Upper_Jaw.mirror = true;
      setRotation(Upper_Jaw, 0F, 0F, 0F);
      Lower_Jaw = new ModelRenderer(this, 0, 20);
      Lower_Jaw.addBox(0F, 0F, 0F, 3, 1, 6);
      Lower_Jaw.setRotationPoint(0.5F, 2.5F, 1F);
      Lower_Jaw.setTextureSize(64, 64);
      Lower_Jaw.mirror = true;
      setRotation(Lower_Jaw, 0F, 0F, 0F);
      Head = new ModelRenderer(this, 0, 0);
      Head.addBox(0F, 0F, 0F, 5, 5, 5);
      Head.setRotationPoint(-0.5F, -1F, 7F);
      Head.setTextureSize(64, 64);
      Head.mirror = true;
      setRotation(Head, 0F, 0F, 0F);
      Teeth = new ModelRenderer(this, 15, 0);
      Teeth.addBox(0F, 0F, 0F, 4, 1, 4);
      Teeth.setRotationPoint(0F, 3F, 0F);
      Teeth.setTextureSize(64, 64);
      Teeth.mirror = true;
      setRotation(Teeth, 0F, 0F, 0F);
      Neck = new ModelRenderer(this, 22, 30);
      Neck.addBox(0F, 0F, 0F, 4, 4, 6);
      Neck.setRotationPoint(0F, -0.5F, 12F);
      Neck.setTextureSize(64, 64);
      Neck.mirror = true;
      setRotation(Neck, -0.5235988F, 0F, 0F);
      Crest = new ModelRenderer(this, 0, 10);
      Crest.addBox(0F, 0F, 0F, 1, 1, 2);
      Crest.setRotationPoint(1.5F, -1F, 5F);
      Crest.setTextureSize(64, 64);
      Crest.mirror = true;
      setRotation(Crest, 0F, 0F, 0F);
      Upper_Body = new ModelRenderer(this, 0, 27);
      Upper_Body.addBox(0F, 0F, 0F, 5, 6, 6);
      Upper_Body.setRotationPoint(-0.5F, 1.5F, 17F);
      Upper_Body.setTextureSize(64, 64);
      Upper_Body.mirror = true;
      setRotation(Upper_Body, -0.5235988F, 0F, 0F);
      Lower_Body = new ModelRenderer(this, 0, 46);
      Lower_Body.addBox(0F, 0F, 0F, 7, 8, 10);
      Lower_Body.setRotationPoint(-1.5F, 2.5F, 19F);
      Lower_Body.setTextureSize(64, 64);
      Lower_Body.mirror = true;
      setRotation(Lower_Body, 0F, 0F, 0F);
      Tail1 = new ModelRenderer(this, 40, 0);
      Tail1.addBox(0F, 0F, 0F, 4, 5, 8);
      Tail1.setRotationPoint(0F, 3F, 29F);
      Tail1.setTextureSize(64, 64);
      Tail1.mirror = true;
      setRotation(Tail1, 0F, 0F, 0F);
      Tail2 = new ModelRenderer(this, 42, 13);
      Tail2.addBox(0F, 0F, 0F, 3, 3, 8);
      Tail2.setRotationPoint(0.5F, 4F, 37F);
      Tail2.setTextureSize(64, 64);
      Tail2.mirror = true;
      setRotation(Tail2, 0F, 0F, 0F);
      Tail3 = new ModelRenderer(this, 50, 24);
      Tail3.addBox(0F, 0F, 0F, 2, 2, 5);
      Tail3.setRotationPoint(1F, 4.5F, 45F);
      Tail3.setTextureSize(64, 64);
      Tail3.mirror = true;
      setRotation(Tail3, 0F, 0F, 0F);
      Thigh1 = new ModelRenderer(this, 22, 11);
      Thigh1.addBox(0F, 0F, 0F, 3, 6, 4);
      Thigh1.setRotationPoint(5F, 5F, 25F);
      Thigh1.setTextureSize(64, 64);
      Thigh1.mirror = true;
      setRotation(Thigh1, -0.2617994F, 0F, 0F);
      Thigh2 = new ModelRenderer(this, 22, 11);
      Thigh2.addBox(0F, 0F, 0F, 3, 6, 4);
      Thigh2.setRotationPoint(-4F, 5F, 25F);
      Thigh2.setTextureSize(64, 64);
      Thigh2.mirror = true;
      setRotation(Thigh2, -0.2617994F, 0F, 0F);
      Calf1 = new ModelRenderer(this, 30, 2);
      Calf1.addBox(0F, 0F, 0F, 2, 6, 3);
      Calf1.setRotationPoint(5F, 10F, 26F);
      Calf1.setTextureSize(64, 64);
      Calf1.mirror = true;
      setRotation(Calf1, -0.2617994F, 0F, 0F);
      Calf2 = new ModelRenderer(this, 30, 2);
      Calf2.addBox(0F, 0F, 0F, 2, 6, 3);
      Calf2.setRotationPoint(-3F, 10F, 26F);
      Calf2.setTextureSize(64, 64);
      Calf2.mirror = true;
      setRotation(Calf2, -0.2617994F, 0F, 0F);
      Foot1 = new ModelRenderer(this, 16, 21);
      Foot1.addBox(0F, 0F, 0F, 3, 2, 7);
      Foot1.setRotationPoint(-4F, 15F, 21.5F);
      Foot1.setTextureSize(64, 64);
      Foot1.mirror = true;
      setRotation(Foot1, 0F, 0F, 0F);
      Foot2 = new ModelRenderer(this, 16, 21);
      Foot2.addBox(0F, 0F, 0F, 3, 2, 7);
      Foot2.setRotationPoint(5F, 15F, 21.5F);
      Foot2.setTextureSize(64, 64);
      Foot2.mirror = true;
      setRotation(Foot2, 0F, 0F, 0F);
      UpperArm1 = new ModelRenderer(this, 40, 24);
      UpperArm1.addBox(0F, 0F, 0F, 2, 4, 3);
      UpperArm1.setRotationPoint(4.5F, 5F, 15F);
      UpperArm1.setTextureSize(64, 64);
      UpperArm1.mirror = true;
      setRotation(UpperArm1, 0F, 0F, 0F);
      UpperArm2 = new ModelRenderer(this, 40, 24);
      UpperArm2.addBox(0F, 0F, 0F, 2, 4, 3);
      UpperArm2.setRotationPoint(-2.5F, 5F, 15F);
      UpperArm2.setTextureSize(64, 64);
      UpperArm2.mirror = true;
      setRotation(UpperArm2, 0F, 0F, 0F);
      LowerArm1 = new ModelRenderer(this, 42, 13);
      LowerArm1.addBox(0F, 0F, 0F, 2, 4, 2);
      LowerArm1.setRotationPoint(4.5F, 8F, 17F);
      LowerArm1.setTextureSize(64, 64);
      LowerArm1.mirror = true;
      setRotation(LowerArm1, -0.5235988F, 0F, 0F);
      LowerArm2 = new ModelRenderer(this, 42, 13);
      LowerArm2.addBox(0F, 0F, 0F, 2, 4, 2);
      LowerArm2.setRotationPoint(-2.5F, 8F, 17F);
      LowerArm2.setTextureSize(64, 64);
      LowerArm2.mirror = true;
      setRotation(LowerArm2, -0.5235988F, 0F, 0F);
      Sail1 = new ModelRenderer(this, 34, 52);
      Sail1.addBox(0F, 0F, 0F, 1, 10, 2);
      Sail1.setRotationPoint(1.5F, -5.5F, 18F);
      Sail1.setTextureSize(64, 64);
      Sail1.mirror = true;
      setRotation(Sail1, 0F, 0F, 0F);
      Sail2 = new ModelRenderer(this, 40, 52);
      Sail2.addBox(0F, 0F, 0F, 1, 10, 2);
      Sail2.setRotationPoint(1.5F, -6.5F, 20F);
      Sail2.setTextureSize(64, 64);
      Sail2.mirror = true;
      setRotation(Sail2, 0F, 0F, 0F);
      Sail3 = new ModelRenderer(this, 46, 52);
      Sail3.addBox(0F, 0F, 0F, 1, 10, 2);
      Sail3.setRotationPoint(1.5F, -7.5F, 22F);
      Sail3.setTextureSize(64, 64);
      Sail3.mirror = true;
      setRotation(Sail3, 0F, 0F, 0F);
      Sail4 = new ModelRenderer(this, 46, 52);
      Sail4.addBox(0F, 0F, 0F, 1, 10, 2);
      Sail4.setRotationPoint(1.5F, -7.5F, 24F);
      Sail4.setTextureSize(64, 64);
      Sail4.mirror = true;
      setRotation(Sail4, 0F, 0F, 0F);
      Sail5 = new ModelRenderer(this, 46, 52);
      Sail5.addBox(0F, 0F, 0F, 1, 10, 2);
      Sail5.setRotationPoint(1.5F, -7.5F, 26F);
      Sail5.setTextureSize(64, 64);
      Sail5.mirror = true;
      setRotation(Sail5, 0F, 0F, 0F);
      Sail6 = new ModelRenderer(this, 40, 52);
      Sail6.addBox(0F, 0F, 0F, 1, 10, 2);
      Sail6.setRotationPoint(1.5F, -6.5F, 28F);
      Sail6.setTextureSize(64, 64);
      Sail6.mirror = true;
      setRotation(Sail6, 0F, 0F, 0F);
      Sail7 = new ModelRenderer(this, 52, 52);
      Sail7.addBox(0F, 0F, 0F, 1, 10, 2);
      Sail7.setRotationPoint(1.5F, -5.5F, 30F);
      Sail7.setTextureSize(64, 64);
      Sail7.mirror = true;
      setRotation(Sail7, 0F, 0F, 0F);
  }
  
  public void render(Entity par1Entity, float par2, float par3, float par4, float par5, float par6, float par7)
  {
	  super.render(par1Entity, par2, par3, par4, par5, par6, par7);
	  setRotationAngles(par2, par3, par4, par5, par6, par7, par1Entity);
    Upper_Jaw.render(par7);
    Lower_Jaw.render(par7);
    Head.render(par7);
    Teeth.render(par7);
    Neck.render(par7);
    Crest.render(par7);
    Upper_Body.render(par7);
    Lower_Body.render(par7);
    Tail1.render(par7);
    Tail2.render(par7);
    Tail3.render(par7);
    Thigh1.render(par7);
    Thigh2.render(par7);
    Calf1.render(par7);
    Calf2.render(par7);
    Foot1.render(par7);
    Foot2.render(par7);
    UpperArm1.render(par7);
    UpperArm2.render(par7);
    LowerArm1.render(par7);
    LowerArm2.render(par7);
    Sail1.render(par7);
    Sail2.render(par7);
    Sail3.render(par7);
    Sail4.render(par7);
    Sail5.render(par7);
    Sail6.render(par7);
    Sail7.render(par7);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity)
  {
    super.setRotationAngles(par1, par2, par3, par4, par5, par6, par7Entity);
  }

}
