// Date: 8/31/2013 11:05:02 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package fossils.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelCarno extends ModelBase
{
  //fields
    ModelRenderer Head;
    ModelRenderer Teeth;
    ModelRenderer Jaw;
    ModelRenderer Horn1;
    ModelRenderer Horn2;
    ModelRenderer Neck;
    ModelRenderer UpperBody;
    ModelRenderer LowerBody;
    ModelRenderer Tail1;
    ModelRenderer Tail2;
    ModelRenderer LeftThigh;
    ModelRenderer RightThigh;
    ModelRenderer LeftLeg;
    ModelRenderer RightLeg;
    ModelRenderer LeftFoot;
    ModelRenderer RightFoot;
    ModelRenderer LeftArm;
    ModelRenderer RightArm;
    ModelRenderer Tail3;
  
  public ModelCarno()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      Head = new ModelRenderer(this, 0, 0);
      Head.addBox(0F, 0F, 0F, 8, 7, 8);
      Head.setRotationPoint(-4.5F, -0.5F, -29F);
      Head.setTextureSize(64, 64);
      Head.mirror = true;
      setRotation(Head, 0F, 0F, 0F);
      Teeth = new ModelRenderer(this, 34, 59);
      Teeth.addBox(0F, 0F, 0F, 8, 4, 1);
      Teeth.setRotationPoint(-4.5F, 7.4F, -29F);
      Teeth.setTextureSize(64, 64);
      Teeth.mirror = true;
      setRotation(Teeth, 1.570796F, 0F, 0F);
      Jaw = new ModelRenderer(this, 0, 15);
      Jaw.addBox(0F, 0F, 0F, 6, 1, 7);
      Jaw.setRotationPoint(-3.5F, 6F, -28F);
      Jaw.setTextureSize(64, 64);
      Jaw.mirror = true;
      setRotation(Jaw, 0F, 0F, 0F);
      Horn1 = new ModelRenderer(this, 24, 0);
      Horn1.addBox(0F, 0F, 0F, 3, 2, 2);
      Horn1.setRotationPoint(-6.5F, -1.5F, -25F);
      Horn1.setTextureSize(64, 64);
      Horn1.mirror = true;
      setRotation(Horn1, 0F, 0F, 0.3490659F);
      Horn2 = new ModelRenderer(this, 24, 0);
      Horn2.addBox(0F, 0F, 0F, 3, 2, 2);
      Horn2.setRotationPoint(2.5F, -0.5F, -25F);
      Horn2.setTextureSize(64, 64);
      Horn2.mirror = true;
      setRotation(Horn2, 0F, 0F, -0.3490659F);
      Neck = new ModelRenderer(this, 20, 4);
      Neck.addBox(0F, 0F, 0F, 5, 6, 12);
      Neck.setRotationPoint(-3F, -0.5F, -22F);
      Neck.setTextureSize(64, 64);
      Neck.mirror = true;
      setRotation(Neck, -0.4363323F, 0F, 0F);
      UpperBody = new ModelRenderer(this, 0, 23);
      UpperBody.addBox(0F, 0F, 0F, 7, 9, 10);
      UpperBody.setRotationPoint(-4F, 3.5F, -12F);
      UpperBody.setTextureSize(64, 64);
      UpperBody.mirror = true;
      setRotation(UpperBody, -0.2617994F, 0F, 0F);
      LowerBody = new ModelRenderer(this, 0, 43);
      LowerBody.addBox(0F, 0F, 0F, 9, 10, 8);
      LowerBody.setRotationPoint(-5F, 5.5F, -6F);
      LowerBody.setTextureSize(64, 64);
      LowerBody.mirror = true;
      setRotation(LowerBody, 0F, 0F, 0F);
      Tail1 = new ModelRenderer(this, 26, 36);
      Tail1.addBox(0F, 0F, 0F, 7, 6, 9);
      Tail1.setRotationPoint(-4F, 5.5F, 1F);
      Tail1.setTextureSize(64, 64);
      Tail1.mirror = true;
      setRotation(Tail1, 0F, 0F, 0F);
      Tail2 = new ModelRenderer(this, 34, 22);
      Tail2.addBox(0F, 0F, 0F, 5, 5, 9);
      Tail2.setRotationPoint(-3F, 5.5F, 10F);
      Tail2.setTextureSize(64, 64);
      Tail2.mirror = true;
      setRotation(Tail2, 0F, 0F, 0F);
      LeftThigh = new ModelRenderer(this, 44, 0);
      LeftThigh.addBox(0F, 0F, 0F, 4, 7, 6);
      LeftThigh.setRotationPoint(4F, 9.5F, -4F);
      LeftThigh.setTextureSize(64, 64);
      LeftThigh.mirror = true;
      setRotation(LeftThigh, -0.1745329F, 0F, 0F);
      RightThigh = new ModelRenderer(this, 44, 0);
      RightThigh.addBox(0F, 0F, 0F, 4, 7, 6);
      RightThigh.setRotationPoint(-9F, 9.5F, -4F);
      RightThigh.setTextureSize(64, 64);
      RightThigh.mirror = true;
      setRotation(RightThigh, -0.1745329F, 0F, 0F);
      LeftLeg = new ModelRenderer(this, 52, 51);
      LeftLeg.addBox(0F, 0F, 0F, 2, 7, 3);
      LeftLeg.setRotationPoint(4F, 15.5F, 0F);
      LeftLeg.setTextureSize(64, 64);
      LeftLeg.mirror = true;
      setRotation(LeftLeg, -0.2617994F, 0F, 0F);
      RightLeg = new ModelRenderer(this, 52, 51);
      RightLeg.addBox(0F, 0F, 0F, 2, 7, 3);
      RightLeg.setRotationPoint(-7F, 15.5F, 0F);
      RightLeg.setTextureSize(64, 64);
      RightLeg.mirror = true;
      setRotation(RightLeg, -0.2617994F, 0F, 0F);
      LeftFoot = new ModelRenderer(this, 34, 51);
      LeftFoot.addBox(0F, 0F, 0F, 3, 2, 6);
      LeftFoot.setRotationPoint(4F, 22F, -4.5F);
      LeftFoot.setTextureSize(64, 64);
      LeftFoot.mirror = true;
      setRotation(LeftFoot, 0F, 0F, 0F);
      RightFoot = new ModelRenderer(this, 34, 51);
      RightFoot.addBox(0F, 0F, 0F, 3, 2, 6);
      RightFoot.setRotationPoint(-8F, 22F, -4.5F);
      RightFoot.setTextureSize(64, 64);
      RightFoot.mirror = true;
      setRotation(RightFoot, 0F, 0F, 0F);
      LeftArm = new ModelRenderer(this, 0, 0);
      LeftArm.addBox(0F, 0F, 0F, 2, 3, 2);
      LeftArm.setRotationPoint(3F, 11.5F, -13F);
      LeftArm.setTextureSize(64, 64);
      LeftArm.mirror = true;
      setRotation(LeftArm, 0.8726646F, 0F, 0F);
      RightArm = new ModelRenderer(this, 0, 0);
      RightArm.addBox(0F, 0F, 0F, 2, 3, 2);
      RightArm.setRotationPoint(-6F, 11.5F, -13F);
      RightArm.setTextureSize(64, 64);
      RightArm.mirror = true;
      setRotation(RightArm, 0.8726646F, 0F, 0F);
      Tail3 = new ModelRenderer(this, 25, 22);
      Tail3.addBox(0F, 0F, 0F, 3, 3, 6);
      Tail3.setRotationPoint(-2F, 6F, 19F);
      Tail3.setTextureSize(64, 64);
      Tail3.mirror = true;
      setRotation(Tail3, 0F, 0F, 0F);
  }
  
  public void render(Entity par1Entity, float par2, float par3, float par4, float par5, float par6, float par7)
  {
	  super.render(par1Entity, par2, par3, par4, par5, par6, par7);
	  setRotationAngles(par2, par3, par4, par5, par6, par7, par1Entity);
    Head.render(par7);
    Teeth.render(par7);
    Jaw.render(par7);
    Horn1.render(par7);
    Horn2.render(par7);
    Neck.render(par7);
    UpperBody.render(par7);
    LowerBody.render(par7);
    Tail1.render(par7);
    Tail2.render(par7);
    LeftThigh.render(par7);
    RightThigh.render(par7);
    LeftLeg.render(par7);
    RightLeg.render(par7);
    LeftFoot.render(par7);
    RightFoot.render(par7);
    LeftArm.render(par7);
    RightArm.render(par7);
    Tail3.render(par7);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity)
  {
    super.setRotationAngles(par1, par2, par3, par4, par5, par6, par7Entity);
  }

}
