// Date: 8/31/2013 6:02:48 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package fossils.main;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelOviraptor extends ModelBase
{
  //fields
    ModelRenderer Head;
    ModelRenderer Beak;
    ModelRenderer Crest;
    ModelRenderer Jaw;
    ModelRenderer Neck;
    ModelRenderer UpperBody;
    ModelRenderer LowerBody;
    ModelRenderer Tail1;
    ModelRenderer Tail2;
    ModelRenderer Thigh1;
    ModelRenderer Thigh2;
    ModelRenderer Calves1;
    ModelRenderer Calves2;
    ModelRenderer Foot1;
    ModelRenderer Foot2;
    ModelRenderer Arm1;
    ModelRenderer Arm12;
    ModelRenderer Arm2;
    ModelRenderer Arm22;
    ModelRenderer FeatherArm1;
    ModelRenderer FeatherArm2;
    ModelRenderer TailFeather;
  
  public ModelOviraptor()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      Head = new ModelRenderer(this, 0, 33);
      Head.addBox(0F, 0F, 0F, 5, 5, 7);
      Head.setRotationPoint(-1.5F, -6F, -7F);
      Head.setTextureSize(64, 64);
      Head.mirror = true;
      setRotation(Head, 0F, 0F, 0F);
      Beak = new ModelRenderer(this, 0, 19);
      Beak.addBox(0F, 0F, 0F, 5, 1, 1);
      Beak.setRotationPoint(-1.5F, -1F, -7F);
      Beak.setTextureSize(64, 64);
      Beak.mirror = true;
      setRotation(Beak, 0.4363323F, 0F, 0F);
      Crest = new ModelRenderer(this, 0, 7);
      Crest.addBox(0F, 0F, 0F, 2, 6, 6);
      Crest.setRotationPoint(0F, -8.5F, -9.5F);
      Crest.setTextureSize(64, 64);
      Crest.mirror = true;
      setRotation(Crest, 0.4363323F, 0F, 0F);
      Jaw = new ModelRenderer(this, 0, 0);
      Jaw.addBox(0F, 0F, 0F, 4, 1, 5);
      Jaw.setRotationPoint(-1F, -1F, -6F);
      Jaw.setTextureSize(64, 64);
      Jaw.mirror = true;
      setRotation(Jaw, 0F, 0F, 0F);
      Neck = new ModelRenderer(this, 30, 0);
      Neck.addBox(0F, 0F, 0F, 2, 10, 3);
      Neck.setRotationPoint(0F, -3F, -1.5F);
      Neck.setTextureSize(64, 64);
      Neck.mirror = true;
      setRotation(Neck, -0.0872665F, 0F, 0F);
      UpperBody = new ModelRenderer(this, 40, 0);
      UpperBody.addBox(0F, 0F, -1F, 6, 6, 6);
      UpperBody.setRotationPoint(-2F, 5F, 0F);
      UpperBody.setTextureSize(64, 64);
      UpperBody.mirror = true;
      setRotation(UpperBody, -0.0872665F, 0F, 0F);
      LowerBody = new ModelRenderer(this, 34, 12);
      LowerBody.addBox(0F, 0F, -1F, 8, 8, 7);
      LowerBody.setRotationPoint(-3F, 5.4F, 5F);
      LowerBody.setTextureSize(64, 64);
      LowerBody.mirror = true;
      setRotation(LowerBody, 0F, 0F, 0F);
      Tail1 = new ModelRenderer(this, 42, 27);
      Tail1.addBox(0F, 0F, -1F, 4, 4, 7);
      Tail1.setRotationPoint(-1F, 6.4F, 11F);
      Tail1.setTextureSize(64, 64);
      Tail1.mirror = true;
      setRotation(Tail1, -0.0872665F, 0F, 0F);
      Tail2 = new ModelRenderer(this, 20, 17);
      Tail2.addBox(0F, 0F, -1F, 2, 2, 10);
      Tail2.setRotationPoint(0F, 7F, 17F);
      Tail2.setTextureSize(64, 64);
      Tail2.mirror = true;
      setRotation(Tail2, 0F, 0F, 0F);
      Thigh1 = new ModelRenderer(this, 26, 29);
      Thigh1.addBox(0F, 0F, -1F, 3, 5, 5);
      Thigh1.setRotationPoint(5F, 8.4F, 7F);
      Thigh1.setTextureSize(64, 64);
      Thigh1.mirror = true;
      setRotation(Thigh1, -0.0872665F, 0F, 0F);
      Thigh2 = new ModelRenderer(this, 26, 29);
      Thigh2.addBox(0F, 0F, -1F, 3, 5, 5);
      Thigh2.setRotationPoint(-6F, 8.4F, 7F);
      Thigh2.setTextureSize(64, 64);
      Thigh2.mirror = true;
      setRotation(Thigh2, -0.0872665F, 0F, 0F);
      Calves1 = new ModelRenderer(this, 18, 29);
      Calves1.addBox(0F, 0F, -1F, 2, 9, 2);
      Calves1.setRotationPoint(5F, 12.4F, 11F);
      Calves1.setTextureSize(64, 64);
      Calves1.mirror = true;
      setRotation(Calves1, -0.1396263F, 0F, 0F);
      Calves2 = new ModelRenderer(this, 18, 29);
      Calves2.addBox(0F, 0F, -1F, 2, 9, 2);
      Calves2.setRotationPoint(-5F, 12.4F, 11F);
      Calves2.setTextureSize(64, 64);
      Calves2.mirror = true;
      setRotation(Calves2, -0.1396263F, 0F, 0F);
      Foot1 = new ModelRenderer(this, 32, 39);
      Foot1.addBox(0F, 0F, 0F, 3, 2, 4);
      Foot1.setRotationPoint(5F, 20F, 7F);
      Foot1.setTextureSize(64, 64);
      Foot1.mirror = true;
      setRotation(Foot1, 0F, 0F, 0F);
      Foot2 = new ModelRenderer(this, 32, 39);
      Foot2.addBox(0F, 0F, 0F, 3, 2, 4);
      Foot2.setRotationPoint(-6F, 20F, 7F);
      Foot2.setTextureSize(64, 64);
      Foot2.mirror = true;
      setRotation(Foot2, 0F, 0F, 0F);
      Arm1 = new ModelRenderer(this, 22, 0);
      Arm1.addBox(0F, 0F, -1F, 2, 4, 2);
      Arm1.setRotationPoint(4F, 8.4F, 0F);
      Arm1.setTextureSize(64, 64);
      Arm1.mirror = true;
      setRotation(Arm1, 0.1396263F, 0F, 0F);
      Arm12 = new ModelRenderer(this, 22, 0);
      Arm12.addBox(0F, 0F, -1F, 2, 4, 2);
      Arm12.setRotationPoint(-4F, 8.4F, 0F);
      Arm12.setTextureSize(64, 64);
      Arm12.mirror = true;
      setRotation(Arm12, 0.1396263F, 0F, 0F);
      Arm2 = new ModelRenderer(this, 22, 6);
      Arm2.addBox(0F, 0F, -1F, 2, 5, 2);
      Arm2.setRotationPoint(4F, 12.2F, 1.8F);
      Arm2.setTextureSize(64, 64);
      Arm2.mirror = true;
      setRotation(Arm2, -0.7853982F, 0F, 0F);
      Arm22 = new ModelRenderer(this, 22, 6);
      Arm22.addBox(0F, 0F, -1F, 2, 5, 2);
      Arm22.setRotationPoint(-4F, 12.2F, 1.8F);
      Arm22.setTextureSize(64, 64);
      Arm22.mirror = true;
      setRotation(Arm22, -0.7853982F, 0F, 0F);
      FeatherArm1 = new ModelRenderer(this, 18, 17);
      FeatherArm1.addBox(0F, 0F, -1F, 1, 5, 5);
      FeatherArm1.setRotationPoint(4F, 13F, 3.3F);
      FeatherArm1.setTextureSize(64, 64);
      FeatherArm1.mirror = true;
      setRotation(FeatherArm1, -0.7853982F, 0F, 0F);
      FeatherArm2 = new ModelRenderer(this, 18, 17);
      FeatherArm2.addBox(0F, 0F, -1F, 1, 5, 5);
      FeatherArm2.setRotationPoint(-3F, 13F, 3.3F);
      FeatherArm2.setTextureSize(64, 64);
      FeatherArm2.mirror = true;
      setRotation(FeatherArm2, -0.7853982F, 0F, 0F);
      TailFeather = new ModelRenderer(this, 36, 38);
      TailFeather.addBox(0F, 0F, -1F, 4, 1, 10);
      TailFeather.setRotationPoint(-1F, 7.5F, 21F);
      TailFeather.setTextureSize(64, 64);
      TailFeather.mirror = true;
      setRotation(TailFeather, 0F, 0F, 0F);
  }
  
  public void render(Entity par1Entity, float par2, float par3, float par4, float par5, float par6, float par7)
  {
	  super.render(par1Entity, par2, par3, par4, par5, par6, par7);
	  setRotationAngles(par2, par3, par4, par5, par6, par7, par1Entity);
    Head.render(par7);
    Beak.render(par7);
    Crest.render(par7);
    Jaw.render(par7);
    Neck.render(par7);
    UpperBody.render(par7);
    LowerBody.render(par7);
    Tail1.render(par7);
    Tail2.render(par7);
    Thigh1.render(par7);
    Thigh2.render(par7);
    Calves1.render(par7);
    Calves2.render(par7);
    Foot1.render(par7);
    Foot2.render(par7);
    Arm1.render(par7);
    Arm12.render(par7);
    Arm2.render(par7);
    Arm22.render(par7);
    FeatherArm1.render(par7);
    FeatherArm2.render(par7);
    TailFeather.render(par7);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity)
  {
    super.setRotationAngles(par1, par2, par3, par4, par5, par6, par7Entity);
  }

}
