// Date: 8/31/2013 5:24:14 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package fossils.main;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelDryo extends ModelBase
{
  //fields
    ModelRenderer Head;
    ModelRenderer Beak;
    ModelRenderer Neck;
    ModelRenderer UpperBody;
    ModelRenderer LowerBody;
    ModelRenderer Tail1;
    ModelRenderer Tail2;
    ModelRenderer Thigh1;
    ModelRenderer Thigh2;
    ModelRenderer Calves1;
    ModelRenderer Calves2;
    ModelRenderer Foot1;
    ModelRenderer Foot2;
    ModelRenderer Arms;
    ModelRenderer Arms2;
  
  public ModelDryo()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Head = new ModelRenderer(this, 0, 0);
      Head.addBox(0F, 0F, 0F, 3, 3, 4);
      Head.setRotationPoint(0F, 9F, -9F);
      Head.setTextureSize(64, 32);
      Head.mirror = true;
      setRotation(Head, 0F, 0F, 0F);
      Beak = new ModelRenderer(this, 0, 7);
      Beak.addBox(0F, 0F, 0F, 2, 2, 2);
      Beak.setRotationPoint(0.5333334F, 10.2F, -10F);
      Beak.setTextureSize(64, 32);
      Beak.mirror = true;
      setRotation(Beak, 0.1745329F, 0F, 0F);
      Neck = new ModelRenderer(this, 0, 11);
      Neck.addBox(0F, 0F, 0F, 2, 2, 4);
      Neck.setRotationPoint(0.5F, 10F, -5F);
      Neck.setTextureSize(64, 32);
      Neck.mirror = true;
      setRotation(Neck, -0.6981317F, 0F, 0F);
      UpperBody = new ModelRenderer(this, 14, 0);
      UpperBody.addBox(0F, 0F, 0F, 4, 4, 4);
      UpperBody.setRotationPoint(-0.5F, 12F, -3F);
      UpperBody.setTextureSize(64, 32);
      UpperBody.mirror = true;
      setRotation(UpperBody, -0.0872665F, 0F, 0F);
      LowerBody = new ModelRenderer(this, 30, 0);
      LowerBody.addBox(0F, 0F, 0F, 5, 5, 5);
      LowerBody.setRotationPoint(-1F, 12.3F, 0F);
      LowerBody.setTextureSize(64, 32);
      LowerBody.mirror = true;
      setRotation(LowerBody, 0F, 0F, 0F);
      Tail1 = new ModelRenderer(this, 0, 17);
      Tail1.addBox(0F, 0F, 0F, 2, 3, 5);
      Tail1.setRotationPoint(0.5F, 12.3F, 5F);
      Tail1.setTextureSize(64, 32);
      Tail1.mirror = true;
      setRotation(Tail1, -0.0872665F, 0F, 0F);
      Tail1 = new ModelRenderer(this, 6, 23);
      Tail1.addBox(0F, 0F, 0F, 1, 1, 8);
      Tail1.setRotationPoint(1F, 13.3F, 9.8F);
      Tail1.setTextureSize(64, 32);
      Tail1.mirror = true;
      setRotation(Tail1, 0F, 0F, 0F);
      Thigh1 = new ModelRenderer(this, 50, 0);
      Thigh1.addBox(0F, 0F, 0F, 2, 4, 3);
      Thigh1.setRotationPoint(4F, 14.3F, 2F);
      Thigh1.setTextureSize(64, 32);
      Thigh1.mirror = true;
      setRotation(Thigh1, -0.1396263F, 0F, 0F);
      Thigh2 = new ModelRenderer(this, 50, 0);
      Thigh2.addBox(0F, 0F, 0F, 2, 4, 3);
      Thigh2.setRotationPoint(-3F, 14.3F, 2F);
      Thigh2.setTextureSize(64, 32);
      Thigh2.mirror = true;
      setRotation(Thigh2, -0.1396263F, 0F, 0F);
      Calves1 = new ModelRenderer(this, 60, 0);
      Calves1.addBox(0F, 0F, 0F, 1, 6, 1);
      Calves1.setRotationPoint(4F, 17.3F, 4F);
      Calves1.setTextureSize(64, 32);
      Calves1.mirror = true;
      setRotation(Calves1, -0.1396263F, 0F, 0F);
      Calves2 = new ModelRenderer(this, 60, 0);
      Calves2.addBox(0F, 0F, 0F, 1, 6, 1);
      Calves2.setRotationPoint(-2F, 17.3F, 4F);
      Calves2.setTextureSize(64, 32);
      Calves2.mirror = true;
      setRotation(Calves2, -0.1396263F, 0F, 0F);
      Foot1 = new ModelRenderer(this, 54, 7);
      Foot1.addBox(0F, 0F, 0F, 2, 1, 3);
      Foot1.setRotationPoint(4F, 22.4F, 1.3F);
      Foot1.setTextureSize(64, 32);
      Foot1.mirror = true;
      setRotation(Foot1, 0F, 0F, 0F);
      Foot2 = new ModelRenderer(this, 54, 7);
      Foot2.addBox(0F, 0F, 0F, 2, 1, 3);
      Foot2.setRotationPoint(-3F, 22.4F, 1.3F);
      Foot2.setTextureSize(64, 32);
      Foot2.mirror = true;
      setRotation(Foot2, 0F, 0F, 0F);
      Arms = new ModelRenderer(this, 30, 0);
      Arms.addBox(0F, 0F, 0F, 1, 3, 1);
      Arms.setRotationPoint(3.5F, 15.3F, -3.2F);
      Arms.setTextureSize(64, 32);
      Arms.mirror = true;
      setRotation(Arms, 0.0872665F, 0F, 0F);
      Arms2 = new ModelRenderer(this, 30, 0);
      Arms2.addBox(0F, 0F, 0F, 1, 3, 1);
      Arms2.setRotationPoint(-1.5F, 15.3F, -3.2F);
      Arms2.setTextureSize(64, 32);
      Arms2.mirror = true;
      setRotation(Arms2, 0.0872665F, 0F, 0F);
  }
  
  public void render(Entity par1Entity, float par2, float par3, float par4, float par5, float par6, float par7)
  {
	  super.render(par1Entity, par2, par3, par4, par5, par6, par7);
	  setRotationAngles(par2, par3, par4, par5, par6, par7, par1Entity);
    Head.render(par7);
    Beak.render(par7);
    Neck.render(par7);
    UpperBody.render(par7);
    LowerBody.render(par7);
    Tail1.render(par7);
    Tail1.render(par7);
    Thigh1.render(par7);
    Thigh2.render(par7);
    Calves1.render(par7);
    Calves2.render(par7);
    Foot1.render(par7);
    Foot2.render(par7);
    Arms.render(par7);
    Arms2.render(par7);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity)
  {
    super.setRotationAngles(par1, par2, par3, par4, par5, par6, par7Entity);
  }

}
